certutil -importpfx "C:\install\certificates\root.pfx" 
certutil -importpfx "C:\install\certificates\wildcard.pfx" 
certutil -importpfx "C:\install\certificates\actiontrail.pfx" 
certutil -importpfx "C:\install\certificates\accountapi.pfx" 
certutil -importpfx "C:\install\certificates\automationserver.pfx" 
certutil -importpfx "C:\install\certificates\billingencrypt.pfx" 
certutil -importpfx "C:\install\certificates\billingapi.pfx" 
certutil -importpfx "C:\install\certificates\billing.pfx" 
certutil -importpfx "C:\install\certificates\guicert.pfx" 
certutil -importpfx "C:\install\certificates\billingapi.pfx" 
certutil -importpfx "C:\install\certificates\stssigning.pfx" 
certutil -importpfx "C:\install\certificates\automationencrypt.pfx" 
certutil -importpfx "C:\install\certificates\hcp.pfx" 
certutil -importpfx "C:\install\certificates\orderapi.pfx" 
certutil -importpfx "C:\install\certificates\sts.pfx" 
certutil -importpfx "C:\install\certificates\userapi.pfx" 
certutil -importpfx "C:\install\certificates\admin.pfx"

