#!/bin/sh

dist=`cat /etc/*-release | egrep ^DISTRIB_CODENAME= | sed 's/.*=//'`

wget http://apt.puppetlabs.com/puppetlabs-release-$dist.deb
sudo dpkg -i puppetlabs-release-precise.deb

sudo apt-get update

sed -i "/templatedir/d" /etc/puppet/puppet.conf

echo -e "
:backends:
  - yaml
:hierarchy:
  - \"nodes/%{::fqdn}\"
  - \"%{::atomia_role}\"
  - \"%{::atomia_brand}_common\"
  - \"%{::kernel}\"
  - common
:yaml:
  :datadir: /etc/puppet/hieradata
" > /etc/puppet/hiera.yaml

echo "
node default {
        hiera_include('classes')
}
" > /etc/puppet/manifests/site.pp

echo "
[atomiacerts]
   path /etc/puppet/atomiacerts
   allow *
[atomia]
   path /etc/puppet/atomia
   allow *
" >> /etc/puppet/fileserver.conf

mkdir -p /etc/puppet/atomia/service_files

echo "mod \"atomia\", :git =>\"git://github.com/atomia/puppet-atomia.git\", :ref => \"stable\"" > Puppetfile

service puppetmaster restart

cd /etc/puppet

gem install librarian-puppet puppet
librarian-puppet install
cp /etc/puppet/modules/atomia/files/default_files/* /etc/puppet/atomia/service_files/

sudo puppet apply -e "class { 'puppetdb': } class { 'puppetdb::master::config': }"
