#!/bin/bash

# This script will download puppetmaster install script
# depending on the OS version that you are using.
# Each script should handle in itself various versions
# of the distro that is used. Example Ubuntu script should
# handle Ubuntu 14.04, 16.04, 18.04 and so on.

source /etc/os-release

if [ $ID = 'ubuntu' ]; then
        echo "Downloading Ubuntu install script..."
        puppet="$(wget -q -O - https://raw.githubusercontent.com/atomia/puppet-atomia/master/setup-puppet-ubuntu)"; echo "$puppet" |  sudo bash
else
        echo "Downloading RHEL install script..."
        puppet="$(wget -q -O - https://raw.githubusercontent.com/atomia/puppet-atomia/master/setup-puppet-rhel)"; echo "$puppet" |  sudo bash
fi

