USE vmail;

ALTER TABLE user
ADD COLUMN quota_id VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN quota_limit BIGINT NOT NULL DEFAULT 0,
ADD COLUMN set_quota BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TRIGGER set_quota_id
BEFORE INSERT ON user
FOR EACH ROW
 SET NEW.quota_id=CONCAT('mb-',(SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA='vmail' AND TABLE_NAME='user'));