#!/bin/sh

# Sync configs, using /etc/atomiadns.conf.powerdnssync if option exist in both
if [ -f "/etc/atomiadns.conf.powerdnssync" ]; then
	if [ -f "/etc/atomiadns.conf" ]; then
		tempconfig=`tempfile || exit 1`

		# options in /etc/atomiadns.conf, if in both then /etc/atomiadns.conf.powerdnssync overrides
		while read k rest; do
			if [ -n "$k" ] && [ -n "$(echo "$k" | grep -v ^"#")" ]; then
				from_generated="$(grep "^$k[[:space:]]" /etc/atomiadns.conf.powerdnssync)"
				if [ -n "$from_generated" ]; then
					echo "$from_generated" >> "$tempconfig"
				else
					echo "$k $rest" >> "$tempconfig"
				fi
			else
				if [ -n "$k" ]; then
					echo "$k $rest" >> "$tempconfig"
				else 
					echo >> "$tempconfig"
				fi
			fi
		done < "/etc/atomiadns.conf"

		# options only in /etc/atomiadns.conf.powerdnssync
		while read k rest; do
			if [ -n "$k" ] && [ -n "$(echo "$k" | grep -v ^"#")" ]; then
				if [ -z "$(grep "^$k[[:space:]]" /etc/atomiadns.conf)" ]; then
					echo "$k $rest" >> "$tempconfig"
				fi
			else
				if [ -n "$k" ]; then
					echo "$k $rest" >> "$tempconfig"
				else 
					echo >> "$tempconfig"
				fi
			fi
		done < "/etc/atomiadns.conf.powerdnssync"

		# move into place if different
		diff "/etc/atomiadns.conf" "$tempconfig" > /dev/null
		if [ $? != 0 ]; then
			chmod 444 "$tempconfig"
			mv "$tempconfig" "/etc/atomiadns.conf"
		fi
	fi
fi

# If we get a nameserver group in $1, check if we subscribe to it, and if not, subscribe and reload zones.
if [ -n "$1" ]; then
	current_group=`atomiapowerdnssync get_server 2>&1 | grep -v ^Warning:`
	if [ -z "$current_group" ]; then
		atomiapowerdnssync add_server "$1"
		atomiapowerdnssync full_reload_online
	fi
fi

